spring.application.name=officepal-api
jwt.secret=OFFICAL_SECRET_KEY_OFFICAL_SECRET_KEY_123
spring.datasource.url=jdbc:postgresql://db:5432/officepal
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=officepal
spring.datasource.password=officepal
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.h2.console.enabled=false
